services:
  apache:
    container_name: apache
    hostname: apache-comparitiko
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www
      - ./apache2:/etc/apache2
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb-despliegue
    image: mariadb:10.11.8
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
