services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www
      - ./apache2:/etc/apache2
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0.38
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql?
      MYSQL_DATABASE: despliegue
      MYSQL_USER: comparitiko
      MYSQL_PASSWORD: gabriel123
    volumes:
      - ./mysql:/var/lib/mysql
